### ISSUE TITLE
Proposal: configure tasks via a YAML file instead of CLI

### ISSUE THREAD

**Issue by dcharbonnier** [alexellis/jaas#29]
it would be very interesting to be able to run yaml files similar to docker-compose

```yaml
 cron:
    networks:
      - sentry_sentry
    image: sentry:8.20.0
    command: "sentry cleanup -l WARNING --days 110"
    environment:
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    deploy:
      timeout: 60s
      remove: true
      placement:
        constraints:
          - node.labels.role == storage
    labels:
      com.xxx.service: "cron"
      com.xxx.stack: "sentry"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://xxx"
        tag: "{{.ImageName}}/{{.ID}}/{{.Name}}"
        labels: "com.xxx.service,com.xxx.stack"
```
